server:
  port: 8001
spring:
  application:
    name: eureka-service
eureka:
  server:
    enable-self-preservation: false
  instance:
    hostname: eureka
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:8001/eureka